version: "3.8"

services:
  # Frontend Test-Service
  frontend-test:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - ./client:/app
    command: >
      /bin/sh -c "
      npm install &&
        npm run test;
      fi
      "

  # Frontend Build- und Bereitstellungsservice
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - frontend-test

  # Backend Test-Service
  backend-test:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: >
      /bin/sh -c "
      npm install &&

        npm run test;
      "

  # Backend Build- und Bereitstellungsservice
  backend:
    build:
      context: . # Root-Verzeichnis, wo dein Backend-Dockerfile liegt
      dockerfile: Dockerfile
    ports:
      - "4000:4000" # Der Backend-Port
    environment:
      - NODE_ENV=production
    depends_on:
      - backend-test
    volumes:
      - .:/app
