name: Deployment Pipeline (Prod)

on:
  push:
    branches: ["master"]

env:
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY  }}
  HOSTNAME: ${{ secrets.HOSTNAME  }}
  USER_NAME: ${{ secrets.USER_NAME  }}

jobs:
  continuous-integration:
    runs-on: ubuntu-22.04
    steps:
      - name: Run Update Script
        run: |
          sshpass -p "${PRIVATE_KEY}" ssh -o StrictHostKeyChecking=no ${USER_NAME}@${HOSTNAME} '
            bash update-frontend1.sh 
            bash update-backend1.sh
          '
